### ISSUE TITLE
[Bug Report] Framework packaging in pom.xml

### ISSUE THREAD

**Issue by seailz** [Negative-Games/Framework#100]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the latest Framework version
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Bug Report Description

https://github.com/Negative-Games/Framework/blob/81d9562cb109c8c2319a390fd47827c105e753be/pom.xml#L7

It's still using the old packaging :/

yo just realised i got #100 pog

**Comment by joeecodes** [comment]
Does this cause any issues when using the API?

**Comment by seailz** [comment]
> Does this cause any issues when using the API?

not really but ig this is the best category i could fit it under?

**Comment by joeecodes** [comment]
So the API works as intended, even with a different groupID?

**Comment by seailz** [comment]
yes

**Comment by joeecodes** [comment]
Then this isn't a bug.
