### ISSUE TITLE
[Feature Request] Nukkit Support

### ISSUE THREAD

**Issue by seailz** [Negative-Games/Framework#103]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the latest Framework version
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

Not sure if this would require/be better as a separate project, but I've recently started getting into Nukkit (Bedrock) development, and a Nukkit framework would be really useful to help make plugins.

### Example Use-Case

```java
N/A
```

**Comment by joeecodes** [comment]
We primarily work on the Java version of Minecraft but it’s not a bad idea. Probably won’t be for a while until we add Nukkit support, if we ever do. For now, we probably won’t add this any time soon.
