### ISSUE TITLE
[Bug Report] Console only annotation not working in SubCommands

### ISSUE THREAD

**Issue by seailz** [Negative-Games/Framework#104]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the latest Framework version
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Bug Report Description

Console only (in CommandInfo) straight up doesn't work.

**Comment by seailz** [comment]
No errors, nothing. Players can still run the command even if it's consoleOnly

**Comment by joeecodes** [comment]
![image](https://user-images.githubusercontent.com/68609292/172061297-a7f92b28-b5a7-4c5c-9172-5b66e3e278db.png)
![NVIDIA_Share_Fi7oqkTS50](https://user-images.githubusercontent.com/68609292/172061304-9d68fd49-a567-434d-8b40-2488c201e4cf.png)
Works for me. 

What version are you using?

**Comment by seailz** [comment]
> ![image](https://user-images.githubusercontent.com/68609292/172061297-a7f92b28-b5a7-4c5c-9172-5b66e3e278db.png) ![NVIDIA_Share_Fi7oqkTS50](https://user-images.githubusercontent.com/68609292/172061304-9d68fd49-a567-434d-8b40-2488c201e4cf.png) Works for me.
> 
> What version are you using?
`2.1.0-BETA-1`

**Comment by joeecodes** [comment]
You realise 2.1.0 stable release is out? Use the latest stable release

**Comment by seailz** [comment]
> You realise 2.1.0 stable release is out? Use the latest stable release

It's an old commission that a client wanted edited, tbh it's not much of a problem but just thought I'd report it either way.

**Comment by seailz** [comment]
If it works for you then you can close this, not too bothered.

**Comment by joeecodes** [comment]
I mean, if it's not working, then it is an issue. 

Can you send the pom and class this is happening in.

**Comment by seailz** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.seailz</groupId>
    <artifactId>[REDACTED}</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>

    <name>REDACTED}</name>

    <description>REDACTED}</description>
    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <url>https://dev.seailz.com</url>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <relocations>
                        <relocation>
                            <pattern>games.negative.framework</pattern>
                            <shadedPattern>com.seailz.lotioncomission</shadedPattern>
                        </relocation>
                    </relocations>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>dmulloy2-repo</id>
            <url>https://repo.dmulloy2.net/repository/public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.8.8-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.Negative-Games</groupId>
            <artifactId>Framework</artifactId>
            <version>2.1.0-BETA-1</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>RELEASE</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.comphenix.protocol</groupId>
            <artifactId>ProtocolLib</artifactId>
            <version>4.7.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
```

Client wanted to keep it private so I'm not able to send the full code but I'll send the CommandInfo
```java
@CommandInfo(
        name = "add",
        consoleOnly = true
)
public class SubAdd extends SubCommand {
```

afaik the contents of the command shouldn't have an effect on this issue.

**Comment by seailz** [comment]
It might be the fact that it's a sub command?
Here's the main command's info
```java
@CommandInfo(
        name = "[REDACTED]",
        args = {"[REDACTED]"},
        aliases = {"[REDACTED]"}
)
public class Command[REDACTED] extends Command 
```

**Comment by joeecodes** [comment]
Seems like it is because it is a sub command

**Comment by NegativeDev** [comment]
Seems like the implementation code for SubCommands isn't fully done for some reason, compare Command and SubCommand and you can see some obvious differences 

This should not be too hard to fix, @joeecodes if you want to take this go for it

**Comment by joeecodes** [comment]
> Seems like the implementation code for SubCommands isn't fully done for some reason, compare Command and SubCommand and you can see some obvious differences
> 
> This should not be too hard to fix, @joeecodes if you want to take this go for it

Already on it. SubCommand doesnt appear to set consoleOnly to true if the annot is present

**Comment by NegativeDev** [comment]
> > Seems like the implementation code for SubCommands isn't fully done for some reason, compare Command and SubCommand and you can see some obvious differences
> > This should not be too hard to fix, @joeecodes if you want to take this go for it
> 
> Already on it. SubCommand doesnt appear to set consoleOnly to true if the annot is present

Same thing with setPlayerOnly as well, guess I forgot to add those when redoing the implementation
