### ISSUE TITLE
[Feature Request] Easier Database Management

### ISSUE THREAD

**Issue by seailz** [Negative-Games/Framework#105]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the latest Framework version
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

Currently the Database class is un-used. This would be really useful for the framework if this class was made functional and could actually be used to interact with a MySQL database.

**Comment by seailz** [comment]
Something like this would be helpful https://github.com/Tallerik/MySQL-API

**Comment by joeecodes** [comment]
If you want to have a crack at this, go ahead.

**Comment by NegativeDev** [comment]
Just make a PR and let us review

**Comment by joeecodes** [comment]
Completed

**Comment by seailz** [comment]
> Completed

big poggers
