### ISSUE TITLE
[Feature Request] Json Util

### ISSUE THREAD

**Issue by seailz** [Negative-Games/Framework#121]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the latest Framework version
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

I'm thinking of adding a JSON util, similar in design to the Database util which I recently worked on. It's main feature will be saving and reading Java objects, easily, however, I'm only going to work on this if this issue gets approved, and I'm worried it wont for a few reasons.

- Loads of other JSON utils already exist
- it's cluttering up the framework

### Example Use-Case

```java
// pseudo code but you get the point
public void foo() {

  JSON json = new JSON(File file);
  json.saveObject(Object object);
  Object o = json.readObject(Class<?> clazz);

}

// or

public void fooo() { 

  JSON json = new JSON(File file);
  json.saveObject(Object object);
  json.save();

  Object o = json.readObject(Class<?> clazz);
}
```

**Comment by seailz** [comment]
actually nvm this might not take me too long

**Comment by seailz** [comment]
(this makes it easier than ObjectCache btw)

**Comment by joeecodes** [comment]
@NegativeDev

**Comment by NegativeDev** [comment]
> (this makes it easier than ObjectCache btw)

not exactly, it seems like it would only save a single object to a json file, with ObjectCache you save an arraylist of the type of thing you want to save

**Comment by joeecodes** [comment]
I don't see this necessary. There's already GSON which is full of JSON utils and adding more than needed isn't always a good thing.
