### ISSUE TITLE
[Feature Request] Selecting Rows In GUIs

### ISSUE THREAD

**Issue by seailz** [Negative-Games/Framework#127]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the latest Framework version
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

There should be a method in the GUI class that allows you to select a specific row, and then select 1-9 in that row, instead of having to calculate which item number it is, therefore making life easier for the user, and making coding faster.

I'll do this myself but I'd like to get approval first

### Example Use-Case

```java
public OmgEpicGUI() {
    ItemStack gold = new ItemStack(Material.GOLD);


    // Row 4, Slot 1
    setItem(4, 1, player -> gold);

    // ==
   
    setItem(37, player -> gold);

    // Adds an item to row 3
    addItem(3, player -> gold);
    
    // setitemclickevent as well ect

}
```

**Comment by joeecodes** [comment]
Looks like a good idea. @NegativeDev any thoughts?

**Comment by seailz** [comment]
> Approved but I'll be doing this

okay
