### ISSUE TITLE
[Feature Request] Flatfile Object Manager

### ISSUE THREAD

**Issue by seailz** [Negative-Games/Framework#128]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the latest Framework version
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

Similar in design to the MySQL object manager I recently created, this util would be able to save and read objects from a YAML file using Bukkit's config framework. I'm willing to work on this (unless negative wants to steal this again hehe) but want approval first.

### Example Use-Case

```java
public void foo() {
   YamlObjectManager manager = new YamlObjectManager(FileConfiguration config);
   manager.saveObject(String path, Object obj);
   
   Object o = manager.readObject(String path, Class<?> clazz);
}
```

**Comment by seailz** [comment]
it'd basically just be a copy-paste of the database one

**Comment by NegativeDev** [comment]
Bukkit's FileConfiguration system already has this ability

**Comment by seailz** [comment]
ah
