### ISSUE TITLE
Changing groupid

### ISSUE THREAD

**Issue by joeecodes** [Negative-Games/Framework#164]
https://github.com/Negative-Games/Framework/blob/00950206ec8de07c3c4316813f995045701e36a9/discord-framework/pom.xml#L7

For this, i'd change it so its just `games.negative.framework` and have the artefact id at `discord-framework` so in Nexus its all in the same parent dir

**Comment by joeecodes** [comment]
@ericlmao

**Comment by ericlmao** [comment]
just the groupid and not the packaging?

**Comment by ericlmao** [comment]
@joeecodes

**Comment by joeecodes** [comment]
just the pom, packaging is all g

**Comment by joeecodes** [comment]
oh, minecraft-framework should be `src/main/java/games/negative/framework/minecraft`

**Comment by ericlmao** [comment]
> oh, minecraft-framework should be `src/main/java/games/negative/framework/minecraft` since its `./discord` for the disc framework

I kept the package the same for the minecraft framework because I didn't want to go through the hassle of changing the imports on projects

**Comment by ericlmao** [comment]
we can make the group id for Discord framework `games.negative.framework` and just keep the packages as `games.negative.framework.discord`
