### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by seailz** [Negative-Games/Framework#74]
```cmd
java.lang.NullPointerException: Cannot invoke "dev.negativekb.api.commands.shortcommands.ShortCommands.addShortSubCommand(dev.negativekb.api.commands.SubCommand, String[])" because the return value of "dev.negativekb.api.commands.shortcommands.ShortCommands.getInstance()" is null```

**Comment by NegativeDev** [comment]
We're not using the `dev.negativekb.api` packaging anymore.

**Comment by IoyoCode** [comment]
> We're not using the `dev.negativekb.api` packaging anymore. 
> 
> 
> 
> And also, please ensure that you run super.onEnable() in your onEnable method.

Got it, thanks.

**Comment by NegativeDev** [comment]
If your issue is fixed, close the issue. I'll leave it open for you to close if you found out your issue is fixed. If not, we can continue this discussion.
