### ISSUE TITLE
GUI Pages

### ISSUE THREAD

**Issue by IoyoCode** [Negative-Games/Framework#86]
There should be some kind of GUI Page system, as making that yourself can be difficult.

Here's how it would work:
There is an option in the super thing where you can choose if you want the GUI to have pages. Then, there should be a `Page` class which you can define what items you want in there. To add a page to your GUI you just have a method like `void addPage(Page page) {}`

I can clarify more if that didn't make sense!

**Comment by IoyoCode** [comment]
If you have a GUI with pages, the way to switch pages would be with two items, one on the left and one on the right which will determine which way you go.

**Comment by joeecodes** [comment]
Already planned https://github.com/Negative-Games/Framework/issues/81

**Comment by IoyoCode** [comment]
This should also be available for Hoppers - if possible. I might make a PR for this later if I feel like it
