### ISSUE TITLE
Intellij Plugin

### ISSUE THREAD

**Issue by IoyoCode** [Negative-Games/Framework#88]
**Is your feature request related to a problem? Please describe.**
What would be really helpful is an Intellij plugin that adds a build thing (like the screenshot below), that automatically imports the key features of a plugin. For example, take this repo: https://github.com/IoyoCode/SimpleEco . Ignore all of the commands and listeners, and just automatically import the core features

**Describe the solution you'd like**
n/a (described above)

**Describe alternatives you've considered**
n/a

**Additional context**
![image](https://user-images.githubusercontent.com/81972974/166947920-f2c6b2c5-4204-4d5b-b35e-5ebf892c2725.png)

**Comment by NegativeDev** [comment]
This issue is not really related to the Framework itself, although I have definitely considered something like this before and probably will make an attempt to do it at some point

**Comment by IoyoCode** [comment]
> This issue is not really related to the Framework itself, although I have definitely considered something like this before and probably will make an attempt to do it at some point

Didn't really know where else to put it
