### ISSUE TITLE
[Feature Request]  Sign GUI

### ISSUE THREAD

**Issue by seailz** [Negative-Games/Framework#96]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the latest Framework version
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

There should be a SignGUI which you can type things into, and can set a specific thing to do on the sign close.

**Comment by seailz** [comment]
(i might make a pull for this if I feel like it)

**Comment by seailz** [comment]
not willing to do this anymore as I am no longer part of this organization.

**Comment by joeecodes** [comment]
@seailz Please add some images and examples so @Negative-Games/developers can add this feature!

**Comment by seailz** [comment]
well that was rude 
![image](https://user-images.githubusercontent.com/81972974/170286508-caf1f6e5-2208-4402-888c-645812275ffb.png)

**Comment by seailz** [comment]
> @seailz Please add some images and examples so @Negative-Games/developers can add this feature!

yep give me a few moments just gonna log on hypixel

**Comment by seailz** [comment]
oop wrong video

**Comment by joeecodes** [comment]
> https://www.youtube.com/watch?v=dyzDPXnR6AA

Gotcha

**Comment by seailz** [comment]
@joeecodes could you assign me to this & is adding protocollib as a depend of the framework all good? I could throw an exception if the user doesn't have protocollib ig

**Comment by joeecodes** [comment]
I think hard requiring them to have ProtocolLib installed isn't the _best_ idea. The concept of this api is to make development as easy as it can. 

What does ProtocolLib do to make this feature work and is it necessarily needed?

If you want to have a crack at it, make your own PR and we'll review it.

**Comment by seailz** [comment]
> I think hard requiring them to have ProtocolLib installed isn't the _best_ idea. The concept of this api is to make development as easy as it can. 
> 
> What does ProtocolLib do to make this feature work and is it necessarily needed?
> 
> If you want to have a crack at it, make your own PR and we'll review it. 

Made a PR - making a fake sign and forcing a player to open it requires packets, and writing & reading the lines also requires packets.

ProtocolLib isn't necessarily **required** but it makes it easier than using the default packet system
