### ISSUE TITLE
[Feature Request] Set plugin messages

### ISSUE THREAD

**Issue by seailz** [Negative-Games/Framework#98]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the latest Framework version
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

Change the plugin messages such as the no permission message

### Example Use-Case

```java
// Appoligies if there are errors/spelling mistakes, I'm coding this in the code block and not in my IDE lol

public class Main extends BasePlugin {

    @Override
    public void onEnable() {
        setPluginMessage(PluginMessage.NO_PERMISSION, "&bYou don't have permission to run that command!");
    }

}
```

**Comment by NegativeDev** [comment]
Already a thing

**Comment by NegativeDev** [comment]
Example:
FrameworkMesssage.NO_PERMISSION.setMessage(new Message("bonk"));

**Comment by seailz** [comment]
oh lol
