### ISSUE TITLE
[Feature Request] Crafting Table GUI

### ISSUE THREAD

**Issue by seailz** [Negative-Games/Framework#99]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the latest Framework version
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

crafting table inventory lol

**Comment by joeecodes** [comment]
Can you give an example.

**Comment by joeecodes** [comment]
> Can you give an example.
> 
> Kinda does say “example use case”

@seailz

**Comment by seailz** [comment]
![image](https://user-images.githubusercontent.com/81972974/170875802-0157dfa4-5824-48f4-be97-feca5dc583d4.png)


> > Can you give an example.
> > Kinda does say “example use case”
> 
> @seailz

**Comment by NegativeDev** [comment]
so.. just a virtual crafting table?

**Comment by seailz** [comment]
> so.. just a virtual crafting table? 

yes

**Comment by joeecodes** [comment]
I wouldn’t say this is a feature needing to be added. 

What context would this be used?

**Comment by seailz** [comment]
> I wouldn’t say this is a feature needing to be added. 
> 
> 
> 
> What context would this be used? 

The command I was using there was `/recipe` from `EssentialsX`. Maybe this could be used if you had custom items on your server, and you wanted to show how to make them for players?

**Comment by joeecodes** [comment]
Fair enough.
